// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Connection.proto

#include "Connection.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
namespace my {
namespace proto {
namespace package {
class ConnectionClientBroadcastSearchRequestDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<ConnectionClientBroadcastSearchRequest> _instance;
} _ConnectionClientBroadcastSearchRequest_default_instance_;
class ConnectionClientBroadcastSearchResponseDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<ConnectionClientBroadcastSearchResponse> _instance;
} _ConnectionClientBroadcastSearchResponse_default_instance_;
}  // namespace package
}  // namespace proto
}  // namespace my
static void InitDefaultsscc_info_ConnectionClientBroadcastSearchRequest_Connection_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::my::proto::package::_ConnectionClientBroadcastSearchRequest_default_instance_;
    new (ptr) ::my::proto::package::ConnectionClientBroadcastSearchRequest();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_ConnectionClientBroadcastSearchRequest_Connection_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_ConnectionClientBroadcastSearchRequest_Connection_2eproto}, {}};

static void InitDefaultsscc_info_ConnectionClientBroadcastSearchResponse_Connection_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::my::proto::package::_ConnectionClientBroadcastSearchResponse_default_instance_;
    new (ptr) ::my::proto::package::ConnectionClientBroadcastSearchResponse();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_ConnectionClientBroadcastSearchResponse_Connection_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_ConnectionClientBroadcastSearchResponse_Connection_2eproto}, {}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_Connection_2eproto[2];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_Connection_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_Connection_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_Connection_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::my::proto::package::ConnectionClientBroadcastSearchRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::my::proto::package::ConnectionClientBroadcastSearchResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::my::proto::package::ConnectionClientBroadcastSearchResponse, ip_),
  PROTOBUF_FIELD_OFFSET(::my::proto::package::ConnectionClientBroadcastSearchResponse, port_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::my::proto::package::ConnectionClientBroadcastSearchRequest)},
  { 5, -1, sizeof(::my::proto::package::ConnectionClientBroadcastSearchResponse)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::my::proto::package::_ConnectionClientBroadcastSearchRequest_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::my::proto::package::_ConnectionClientBroadcastSearchResponse_default_instance_),
};

const char descriptor_table_protodef_Connection_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\020Connection.proto\022\020my.proto.package\032\017Pa"
  "cketsId.proto\".\n&ConnectionClientBroadca"
  "stSearchRequest:\004\200\265\030\n\"I\n\'ConnectionClien"
  "tBroadcastSearchResponse\022\n\n\002ip\030\001 \001(\t\022\014\n\004"
  "port\030\002 \001(\r:\004\200\265\030\013b\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_Connection_2eproto_deps[1] = {
  &::descriptor_table_PacketsId_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_Connection_2eproto_sccs[2] = {
  &scc_info_ConnectionClientBroadcastSearchRequest_Connection_2eproto.base,
  &scc_info_ConnectionClientBroadcastSearchResponse_Connection_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_Connection_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_Connection_2eproto = {
  false, false, descriptor_table_protodef_Connection_2eproto, "Connection.proto", 184,
  &descriptor_table_Connection_2eproto_once, descriptor_table_Connection_2eproto_sccs, descriptor_table_Connection_2eproto_deps, 2, 1,
  schemas, file_default_instances, TableStruct_Connection_2eproto::offsets,
  file_level_metadata_Connection_2eproto, 2, file_level_enum_descriptors_Connection_2eproto, file_level_service_descriptors_Connection_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_Connection_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_Connection_2eproto)), true);
namespace my {
namespace proto {
namespace package {

// ===================================================================

class ConnectionClientBroadcastSearchRequest::_Internal {
 public:
};

ConnectionClientBroadcastSearchRequest::ConnectionClientBroadcastSearchRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:my.proto.package.ConnectionClientBroadcastSearchRequest)
}
ConnectionClientBroadcastSearchRequest::ConnectionClientBroadcastSearchRequest(const ConnectionClientBroadcastSearchRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:my.proto.package.ConnectionClientBroadcastSearchRequest)
}

void ConnectionClientBroadcastSearchRequest::SharedCtor() {
}

ConnectionClientBroadcastSearchRequest::~ConnectionClientBroadcastSearchRequest() {
  // @@protoc_insertion_point(destructor:my.proto.package.ConnectionClientBroadcastSearchRequest)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void ConnectionClientBroadcastSearchRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void ConnectionClientBroadcastSearchRequest::ArenaDtor(void* object) {
  ConnectionClientBroadcastSearchRequest* _this = reinterpret_cast< ConnectionClientBroadcastSearchRequest* >(object);
  (void)_this;
}
void ConnectionClientBroadcastSearchRequest::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void ConnectionClientBroadcastSearchRequest::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ConnectionClientBroadcastSearchRequest& ConnectionClientBroadcastSearchRequest::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_ConnectionClientBroadcastSearchRequest_Connection_2eproto.base);
  return *internal_default_instance();
}


void ConnectionClientBroadcastSearchRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:my.proto.package.ConnectionClientBroadcastSearchRequest)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ConnectionClientBroadcastSearchRequest::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* ConnectionClientBroadcastSearchRequest::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:my.proto.package.ConnectionClientBroadcastSearchRequest)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:my.proto.package.ConnectionClientBroadcastSearchRequest)
  return target;
}

size_t ConnectionClientBroadcastSearchRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:my.proto.package.ConnectionClientBroadcastSearchRequest)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ConnectionClientBroadcastSearchRequest::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:my.proto.package.ConnectionClientBroadcastSearchRequest)
  GOOGLE_DCHECK_NE(&from, this);
  const ConnectionClientBroadcastSearchRequest* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<ConnectionClientBroadcastSearchRequest>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:my.proto.package.ConnectionClientBroadcastSearchRequest)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:my.proto.package.ConnectionClientBroadcastSearchRequest)
    MergeFrom(*source);
  }
}

void ConnectionClientBroadcastSearchRequest::MergeFrom(const ConnectionClientBroadcastSearchRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:my.proto.package.ConnectionClientBroadcastSearchRequest)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

}

void ConnectionClientBroadcastSearchRequest::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:my.proto.package.ConnectionClientBroadcastSearchRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ConnectionClientBroadcastSearchRequest::CopyFrom(const ConnectionClientBroadcastSearchRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:my.proto.package.ConnectionClientBroadcastSearchRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ConnectionClientBroadcastSearchRequest::IsInitialized() const {
  return true;
}

void ConnectionClientBroadcastSearchRequest::InternalSwap(ConnectionClientBroadcastSearchRequest* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
}

::PROTOBUF_NAMESPACE_ID::Metadata ConnectionClientBroadcastSearchRequest::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

class ConnectionClientBroadcastSearchResponse::_Internal {
 public:
};

ConnectionClientBroadcastSearchResponse::ConnectionClientBroadcastSearchResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:my.proto.package.ConnectionClientBroadcastSearchResponse)
}
ConnectionClientBroadcastSearchResponse::ConnectionClientBroadcastSearchResponse(const ConnectionClientBroadcastSearchResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ip_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_ip().empty()) {
    ip_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_ip(), 
      GetArena());
  }
  port_ = from.port_;
  // @@protoc_insertion_point(copy_constructor:my.proto.package.ConnectionClientBroadcastSearchResponse)
}

void ConnectionClientBroadcastSearchResponse::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_ConnectionClientBroadcastSearchResponse_Connection_2eproto.base);
  ip_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  port_ = 0u;
}

ConnectionClientBroadcastSearchResponse::~ConnectionClientBroadcastSearchResponse() {
  // @@protoc_insertion_point(destructor:my.proto.package.ConnectionClientBroadcastSearchResponse)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void ConnectionClientBroadcastSearchResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  ip_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void ConnectionClientBroadcastSearchResponse::ArenaDtor(void* object) {
  ConnectionClientBroadcastSearchResponse* _this = reinterpret_cast< ConnectionClientBroadcastSearchResponse* >(object);
  (void)_this;
}
void ConnectionClientBroadcastSearchResponse::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void ConnectionClientBroadcastSearchResponse::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ConnectionClientBroadcastSearchResponse& ConnectionClientBroadcastSearchResponse::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_ConnectionClientBroadcastSearchResponse_Connection_2eproto.base);
  return *internal_default_instance();
}


void ConnectionClientBroadcastSearchResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:my.proto.package.ConnectionClientBroadcastSearchResponse)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ip_.ClearToEmpty();
  port_ = 0u;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ConnectionClientBroadcastSearchResponse::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // string ip = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_ip();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "my.proto.package.ConnectionClientBroadcastSearchResponse.ip"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // uint32 port = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          port_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* ConnectionClientBroadcastSearchResponse::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:my.proto.package.ConnectionClientBroadcastSearchResponse)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string ip = 1;
  if (this->ip().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_ip().data(), static_cast<int>(this->_internal_ip().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "my.proto.package.ConnectionClientBroadcastSearchResponse.ip");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_ip(), target);
  }

  // uint32 port = 2;
  if (this->port() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(2, this->_internal_port(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:my.proto.package.ConnectionClientBroadcastSearchResponse)
  return target;
}

size_t ConnectionClientBroadcastSearchResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:my.proto.package.ConnectionClientBroadcastSearchResponse)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string ip = 1;
  if (this->ip().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_ip());
  }

  // uint32 port = 2;
  if (this->port() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_port());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ConnectionClientBroadcastSearchResponse::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:my.proto.package.ConnectionClientBroadcastSearchResponse)
  GOOGLE_DCHECK_NE(&from, this);
  const ConnectionClientBroadcastSearchResponse* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<ConnectionClientBroadcastSearchResponse>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:my.proto.package.ConnectionClientBroadcastSearchResponse)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:my.proto.package.ConnectionClientBroadcastSearchResponse)
    MergeFrom(*source);
  }
}

void ConnectionClientBroadcastSearchResponse::MergeFrom(const ConnectionClientBroadcastSearchResponse& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:my.proto.package.ConnectionClientBroadcastSearchResponse)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.ip().size() > 0) {
    _internal_set_ip(from._internal_ip());
  }
  if (from.port() != 0) {
    _internal_set_port(from._internal_port());
  }
}

void ConnectionClientBroadcastSearchResponse::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:my.proto.package.ConnectionClientBroadcastSearchResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ConnectionClientBroadcastSearchResponse::CopyFrom(const ConnectionClientBroadcastSearchResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:my.proto.package.ConnectionClientBroadcastSearchResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ConnectionClientBroadcastSearchResponse::IsInitialized() const {
  return true;
}

void ConnectionClientBroadcastSearchResponse::InternalSwap(ConnectionClientBroadcastSearchResponse* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  ip_.Swap(&other->ip_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  swap(port_, other->port_);
}

::PROTOBUF_NAMESPACE_ID::Metadata ConnectionClientBroadcastSearchResponse::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace package
}  // namespace proto
}  // namespace my
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::my::proto::package::ConnectionClientBroadcastSearchRequest* Arena::CreateMaybeMessage< ::my::proto::package::ConnectionClientBroadcastSearchRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::my::proto::package::ConnectionClientBroadcastSearchRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::my::proto::package::ConnectionClientBroadcastSearchResponse* Arena::CreateMaybeMessage< ::my::proto::package::ConnectionClientBroadcastSearchResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::my::proto::package::ConnectionClientBroadcastSearchResponse >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
