// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PacketsId.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_PacketsId_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_PacketsId_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3017000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3017000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/descriptor.pb.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_PacketsId_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_PacketsId_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_PacketsId_2eproto;
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE
namespace my {
namespace proto {
namespace package {

enum PackageId : int {
  UNKNOWN_MESSAGE_ID = 0,
  CONNECTION_REQUEST = 10,
  CONNECTION_RESPONSE = 11,
  CONNECTION_PING = 12,
  CONNECTION_PONG = 13,
  CONNECTION_DISCONNECT = 14,
  MOUSE_POSITION_MESSAGE = 100,
  MOUSE_CLICK_MESSAGE = 101,
  PackageId_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  PackageId_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool PackageId_IsValid(int value);
constexpr PackageId PackageId_MIN = UNKNOWN_MESSAGE_ID;
constexpr PackageId PackageId_MAX = MOUSE_CLICK_MESSAGE;
constexpr int PackageId_ARRAYSIZE = PackageId_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* PackageId_descriptor();
template<typename T>
inline const std::string& PackageId_Name(T enum_t_value) {
  static_assert(::std::is_same<T, PackageId>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function PackageId_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    PackageId_descriptor(), enum_t_value);
}
inline bool PackageId_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, PackageId* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<PackageId>(
    PackageId_descriptor(), name, value);
}
// ===================================================================


// ===================================================================

static const int kPackageIdFieldNumber = 50000;
extern ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::EnumTypeTraits< ::my::proto::package::PackageId, ::my::proto::package::PackageId_IsValid>, 14, false >
  package_id;

// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace package
}  // namespace proto
}  // namespace my

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::my::proto::package::PackageId> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::my::proto::package::PackageId>() {
  return ::my::proto::package::PackageId_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_PacketsId_2eproto
